version: '3'
services:
  database:
    container_name: recharge-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=recharge
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
  backend:
    depends_on:
      - database
    container_name: recharge-backend
    image: simohin/recharge-backend
    environment:
      dwolla.key: 'YrjABR4ePuqNQKDkR0wCqC1TBiTiflzxesFrMaPar6aEP7qzM5'
      dwolla.secret: '4j1ystGAgWqplzxZzLOtR5UBht6iaVw66ZR2mgWTq9hMB9JAt8'
      plaid.client: '639c1b2155c82a0013835743'
      plaid.secret: 'af08f054b16e11aa193734c94f43cb'
  frontend:
    container_name: recharge-frontend
    image: simohin/recharge-frontend:local
    ports:
      - '3000:80'
