spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recharge
    username: recharge
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
